functionsDirectory = "C:\\Users\\user\\Downloads\\motivator\\netlify\\functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\user\\Downloads\\motivator"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Static site — no build required'"
functions = "C:\\Users\\user\\Downloads\\motivator\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/bot"
to = "/.netlify/functions/bot"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]